name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=jabegel_cookiecutter
            -Dsonar.organization=jabegel
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
