security:
  ignore-vulnerabilities:
    70612:
      # Jinja2 `.from_string()` may be "dangerous".
      reason: "Rendering potentially-unsafe user-supplied templates is core functionality."
    76752:
      reason: "Temporarily ignoring setuptools vulnerability while waiting for fix"
